### ISSUE TITLE
Several errors when compiling CIB library

### ISSUE THREAD

**Issue by elbeno** [jefftrull/tspew#2]
I'm compiling https://github.com/intel/compile-time-init-build
To check out tspew, I introduced an error by putting `Js - 1` in the pack expansion at https://github.com/intel/compile-time-init-build/blob/main/include/cib/tuple_algorithms.hpp#L250
Lots of errors from tspew resulted, message buffer follows.

--
found a type: |18446744073709551615UL| but it does not fill the quoted expression |18446744073709551615UL < sizeof...(Ts)|
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 2316, 4366
error in process filter: Scan error: "Unbalanced parentheses", 2316, 4366
found a type: |18446744073709551615UL| but it does not fill the quoted expression |18446744073709551615UL < sizeof...(Ts)|
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>>::operator[]<18446744073709551615UL>|
error in process filter: setq: Wrong type argument: number-or-marker-p, nil
error in process filter: Wrong type argument: number-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>>::operator[]<18446744073709551615UL>|
found a function: |cib::chunk_by(cib::tuple<cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>> &&)| but it does not fill the quoted expression |cib::chunk_by(cib::tuple<cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>> &&)::(anonymous class)::operator()(std::index_sequence<0UL>)::(anonymous class)::operator()<0UL, 1UL>|
found a function: |cib::chunk_by(cib::tuple<cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>> &&)| but it does not fill the quoted expression |cib::chunk_by(cib::tuple<cib::detail::extend<TestCallback<0>>, cib::detail::extend<TestCallback<0>, SimpleConfig::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/nexus.cpp:22:38)>> &&)::(anonymous class)::operator()<0UL>|
found a type: |18446744073709551615| but it does not fill the quoted expression |18446744073709551615 < 2|
found a type: |18446744073709551615UL| but it does not fill the quoted expression |18446744073709551615UL < sizeof...(Ts)|
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1, 2, 3, 4, 5>, cib::detail::index_function_list<>, int, int, int, double, double, bool>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1, 2, 3, 4, 5>, cib::detail::index_function_list<>, int, int, int, double, double, bool>::operator[]<18446744073709551615UL>|
found a function: |cib::chunk_by(const cib::tuple<int, int, int, double, double, bool> &)| but it does not fill the quoted expression |cib::chunk_by(const cib::tuple<int, int, int, double, double, bool> &)::(anonymous class)::operator()(std::index_sequence<0UL, 1UL, 2UL>)::(anonymous class)::operator()<0UL, 1UL, 2UL>|
found a function: |cib::chunk_by(const cib::tuple<int, int, int, double, double, bool> &)| but it does not fill the quoted expression |cib::chunk_by(const cib::tuple<int, int, int, double, double, bool> &)::(anonymous class)::operator()<0UL, 1UL, 2UL>|
found a type: |18446744073709551615| but it does not fill the quoted expression |18446744073709551615 < 6|
found a type: |18446744073709551615UL| but it does not fill the quoted expression |18446744073709551615UL < sizeof...(Ts)|
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<say_message>, cib::detail::extend<say_message, say_hello_world::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/readme_hello_world.cpp:18:34)>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<say_message>, cib::detail::extend<say_message, say_hello_world::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/readme_hello_world.cpp:18:34)>>::operator[]<18446744073709551615UL>|
found a function: |cib::chunk_by(cib::tuple<cib::detail::extend<say_message>, cib::detail::extend<say_message, say_hello_world::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/readme_hello_world.cpp:18:34)>> &&)| but it does not fill the quoted expression |cib::chunk_by(cib::tuple<cib::detail::extend<say_message>, cib::detail::extend<say_message, say_hello_world::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/readme_hello_world.cpp:18:34)>> &&)::(anonymous class)::operator()(std::index_sequence<0UL>)::(anonymous class)::operator()<0UL, 1UL>|
found a function: |cib::chunk_by(cib::tuple<cib::detail::extend<say_message>, cib::detail::extend<say_message, say_hello_world::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/readme_hello_world.cpp:18:34)>> &&)| but it does not fill the quoted expression |cib::chunk_by(cib::tuple<cib::detail::extend<say_message>, cib::detail::extend<say_message, say_hello_world::(lambda at /home/bdeane/dev/compile-time-init-build/test/cib/readme_hello_world.cpp:18:34)>> &&)::(anonymous class)::operator()<0UL>|
found a type: |18446744073709551615| but it does not fill the quoted expression |18446744073709551615 < 2|
found a type: |18446744073709551615UL| but it does not fill the quoted expression |18446744073709551615UL < sizeof...(Ts)|
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha, flow::milestone_base>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha, flow::milestone_base>>::operator[]<18446744073709551615UL>|
found a function: |cib::chunk_by(cib::tuple<cib::detail::extend<(anonymous namespace)::TestFlowAlpha>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha, flow::milestone_base>> &&)| but it does not fill the quoted expression |cib::chunk_by(cib::tuple<cib::detail::extend<(anonymous namespace)::TestFlowAlpha>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha, flow::milestone_base>> &&)::(anonymous class)::operator()(std::index_sequence<0UL>)::(anonymous class)::operator()<0UL, 1UL>|
found a function: |cib::chunk_by(cib::tuple<cib::detail::extend<(anonymous namespace)::TestFlowAlpha>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha, flow::milestone_base>> &&)| but it does not fill the quoted expression |cib::chunk_by(cib::tuple<cib::detail::extend<(anonymous namespace)::TestFlowAlpha>, cib::detail::extend<(anonymous namespace)::TestFlowAlpha, flow::milestone_base>> &&)::(anonymous class)::operator()<0UL>|
found a type: |18446744073709551615| but it does not fill the quoted expression |18446744073709551615 < 2|
found a type: |18446744073709551615UL| but it does not fill the quoted expression |18446744073709551615UL < sizeof...(Ts)|
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
error in process filter: setq: Wrong type argument: number-or-marker-p, nil
error in process filter: Wrong type argument: number-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |>, msg::in_t<msg::field<sc::string_constant<char, |
no instructions produced for region |>, msg::in_t<msg::field<sc::string_constant<char, |
error in process filter: let: Wrong type argument: integer-or-marker-p, nil
error in process filter: Wrong type argument: integer-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |>, msg::in_t<msg::field<sc::string_constant<char, |
no instructions produced for region |>, msg::in_t<msg::field<sc::string_constant<char, |
error in process filter: let: Wrong type argument: integer-or-marker-p, nil
error in process filter: Wrong type argument: integer-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |>, msg::in_t<msg::field<sc::string_constant<char, |
no instructions produced for region |>, msg::in_t<msg::field<sc::string_constant<char, |
error in process filter: let: Wrong type argument: integer-or-marker-p, nil
error in process filter: Wrong type argument: integer-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |>, msg::in_t<msg::field<sc::string_constant<char, |
no instructions produced for region |>, msg::in_t<msg::field<sc::string_constant<char, |
error in process filter: let: Wrong type argument: integer-or-marker-p, nil
error in process filter: Wrong type argument: integer-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |>, msg::in_t<msg::field<sc::string_constant<char, |
no instructions produced for region |>, msg::in_t<msg::field<sc::string_constant<char, |
error in process filter: let: Wrong type argument: integer-or-marker-p, nil
error in process filter: Wrong type argument: integer-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |>, msg::in_t<msg::field<sc::string_constant<char, |
no instructions produced for region |>, msg::in_t<msg::field<sc::string_constant<char, |
error in process filter: let: Wrong type argument: integer-or-marker-p, nil
error in process filter: Wrong type argument: integer-or-marker-p, nil
found a type: |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, 'T', 'e', 's', 't', 'C', 'a', 'l', 'l', 'b', 'a', 'c', 'k'>, msg::in_t<msg::field<sc::string_constant<char, 't', 'e', 's', 't', '_', 'i', 'd', '_', 'f', 'i', 'e', 'l', 'd'>, 0, 31, 24, unsigned int, 0>, unsigned int, 128>, msg::(lambda at /home/bdeane/dev/compile-time-init-build/test/msg/indexed_builder.cpp:31:5)>>>::operator[]| but it does not fill the quoted expression |cib::detail::tuple_impl<std::integer_sequence<unsigned long, 0, 1>, cib::detail::index_function_list<>, cib::detail::extend<msg::test_service>, cib::detail::extend<msg::test_service, msg::indexed_callback_t<sc::string_constant<char, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |, |
no instructions produced for region |, |
Found a quoted expression I don’t understand: |>, msg::in_t<msg::field<sc::string_constant<char, |
no instructions produced for region |>, msg::in_t<msg::field<sc::string_constant<char, |
error in process filter: let: Wrong type argument: integer-or-marker-p, nil
error in process filter: Wrong type argument: integer-or-marker-p, nil

**Comment by elbeno** [comment]
I'm using cmake and ninja to drive clang-16.0.6 from apt.llvm.org in case that is relevant.

**Comment by jefftrull** [comment]
The current set of errors have been resolved. I look forward to seeing the next set :)
