### ISSUE TITLE
tspew breaking cpp-auto-include

### ISSUE THREAD

**Issue by elbeno** [jefftrull/tspew#3]
Loading tspew for some reason causes cpp-auto-include functionality (https://github.com/elbeno/dotemacs/blob/main/.emacs.d/site-lisp/cpp-auto-include.el) to break.
Specifically it seems that after loading tspew, headers are never inserted. Because cpp-auto-include doesn't find the appropriate regex matches?

**Comment by jefftrull** [comment]
Thanks for the bug report! I'm stuck trying to reproduce - I can't get it working even without tspew :) Can you give me a quick set of steps? It looks like your version and the one in the orphanage have diverged. Thanks.

**Comment by jefftrull** [comment]
OK I can reproduce it now. The animated gif in the orphanage is very misleading as to the usage!

**Comment by jefftrull** [comment]
Bisected this to inadvertent modification of the global syntax table (!). Seems to be fixed.
